name: PHP docker CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "clone repo"
        uses: "actions/checkout@v3"

      - name: "start docker"
        run: docker compose up -d --build

      - name: "check containers"
        run: docker ps

      - name: "wait containers"
        run: sleep 15

      - name: "install require"
        run: docker exec -t lab5_php composer install

      - name: "run tests"
        run: docker exec lab5_php vendor/bin/phpunit

      - name: "stop containers"
        if: always()
        run: docker compose down