name: PHP docker CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "clone repo"
        uses: "actions/checkout@v3"

      - name: "start docker"
        run: docker compose up -d --build

      - name: "check containers"
        run: docker ps

      - name: "run tests"
        run: docker exec -t study-web-2026-php-1 ../vendor/bin/phpunit

      - name: "stop containers"
        if: always()
        run: docker compose down